#define MAX(a, b) ((a) > (b) ? (a) : (b))

//OP(name, str  ,num_op, dif                                                                          , size                , prior,  math            , start    , midle   , end)
  OP(ADD , "+"  , 0 , ADD(D(L), D(R))                                                                 , 3 * (Ls + Rs)       , 0   ,   left+right      , ""       , " + "   , "" )
  OP(SUB , "-"  , 1 , SUB(D(L), D(R))                                                                 , 3 * (Ls + Rs)       , 0   ,   left-right      , ""       , " - "   , "" )
  OP(MUL , "*"  , 2 , ADD(MUL(C(L), D(R)) , MUL(D(L), C(L)))                                          , 3 * (Ls + Rs)       , 1   ,   left*right      , ""       , " * "   , "" )
  OP(DIV , "/"  , 3 , MUL(DIV(SUB(MUL(C(L), D(R)) , MUL(D(L), C(L))), POW(C(R), CONST(2))), CONST(-1)), 2 * MAX(Ls , Rs)    , 1   ,   left/right      , "\\frac{", "}{"    , "}")
  OP(SQRT, "√"  , 4 , MUL(D(R), DIV(CONST(1), MUL(CONST(2), C(node))))                                , 8 * Ls + 2 * Rs     , 4   ,   sqrt(right)     , ""       , "sqrt{" , "}")
  OP(SIN , "sin", 5 , MUL(D(R), COS(C(R)))                                                            , 2*Rs + 3            , 4   ,   sin(right)      , ""       , "\\sin(", ")")
  OP(COS , "cos", 6 , MUL(D(R), MUL(CONST(-1), SIN(C(R))))                                            , 2*Rs + 3            , 4   ,   cos(right)      , ""       , "\\cos(", ")")
  OP(TAN , "tg" , 7 , MUL(D(R), DIV(CONST(1), POW(COS(C(R)), CONST(2))))                              , 2*Rs + 3            , 4   ,   tan(right)      , ""       , "\\tg(" , ")")
  OP(COT , "ctg", 8 , MUL(D(R), MUL(CONST(-1), SIN(DIV(CONST(1), POW(SIN(C(R)), CONST(2))))))         , 2*Rs + 3            , 4   ,   1/tan(right)    , ""       , "\\ctg(", ")")
  OP(POW , "^"  , 9 , MUL(C(node), ADD(MUL(D(R), LOG(E, C(L))), MUL(DIV(Der(L), C(L)), C(R))))        , 8 * Ls + 2 * Rs     , 2   ,   pow(left, right), "("       , ")^{"    , "}")
  OP(LOG , "log", 10, MUL(D(R), DIV(CONST(1), C(R)))                                                  , 2*Rs + 3            , 4   ,   log(right)      , "\\log_{", "}("    , ")")
